name: glutenfreeyogaretreat
favicon: null
layout_spectrum: 0.8339737399946898
typography_spectrum: 0.37036143289878964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8450777728576213
  lightness: 0.20469044777564704
  saturation: 0.37879152689129114
  rhythmicContrast: 0.5803854793775827
purpose: []
